root = "."
testdata_dir = "testdata"
tmp_dir = "temp"

[build]
  args_bin = []
  bin = "true"
  cmd = "templ generate --notify-proxy -proxy=http://localhost:8080 --proxyport=3000 --proxybind=localhost"
  delay = 1000
  exclude_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["server/public"]
  include_ext = ["html", "js", "css"]
  include_file = []
  kill_delay = "1s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 1000
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
